server:
  port: 8090

spring:
  application:
    name: service-b
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://localhost:9090

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG