server:
  port: 8080

spring:
  application:
    name: service-a
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://localhost:9090

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG